home/urls.py
from django.urls import path
from . import views
app_name = "home"

#Url_config
urlpatterns = [
    path('index/', views.say_hello, name="index"),
    path('contact/', views.contact, name="contact")
]

mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from home import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('home.urls', namespace='home')),
    path('vege/', include('vege.urls', namespace='vege')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

vege/urls.py
from django.urls import path
from . import views
app_name = "vege"

#Url_config
urlpatterns = [
    path('recipe/', views.recipe, name="recipe"),
    path('delete_recipe/<int:id>/', views.delete_recipe, name='delete_recipe'),
    path('update_recipe/<int:id>/', views.update_recipe, name='update_recipe'),
    path('login_page/', views.login_page, name='login_page'),
    path('register/', views.register, name='register'),
    path('logout_page/', views.logout_page, name='logout_page'),

]

home/models.py
from django.db import models

# Create your models here.
class Student(models.Model):
    name = models.CharField(max_length=100)
    age = models.IntegerField()
    email =  models.EmailField(null=True, blank=True)
    address = models.TextField(null=True, blank=True)
    # profile_image = models.ImageField()
    # file = models.FileField()

class Car(models.Model):
    car_name = models.CharField()
    speed = models.IntegerField()

    def __str__(self):
        return f"Car: {self.car_name}, Speed: {self.speed} km/h"

vege/models.py
from django.db import models
from django.contrib.auth.models import User

class Recipe(models.Model):
    user = models.ForeignKey(User, on_delete=models.SET_NULL,null=True, blank=True)
    recipe_name = models.CharField()
    recipe_description = models.TextField()
    recipe_image = models.ImageField()
    recipe_view_count = models.IntegerField(default=1)

home/views.py
from django.shortcuts import render
from django.http import HttpResponse

def say_hello(request):
    people = [
        {'Name' : 'Akhil', 'Designation': 'Python Developer', 'Age' : 23},
        {'Name' : 'Jay', 'Designation': 'FullStack', 'Age' : 44},
        # {'Name' : 'Ramesh', 'Designation': 'RPA Developer', 'Age' : 32},
        # {'Name' : 'Chirag', 'Designation': 'UI/UX Developer', 'Age' : 25},
        # {'Name' : 'Jayesh', 'Designation': 'React', 'Age' : 49}
    ]
    for peoples in people:
        print(people)

    return render(request, 'index.html', context={'peoples' : people})
    # return HttpResponse("Hello, world!")

def contact(request):
    return render(request,'contact.html')

vege/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
from .models import Recipe
from django.contrib.auth.decorators import login_required

@login_required(login_url='/vege/login/')
def recipe(request):
    if request.method == "POST":
        data = request.POST
        recipe_name = data.get('recipe_name')
        recipe_description = data.get('recipe_description')
        recipe_image = request.FILES.get('recipe_image')

        # Save to database
        Recipe.objects.create(
            recipe_name=recipe_name,
            recipe_description=recipe_description,
            recipe_image=recipe_image
        )
        return redirect('/vege/recipe/')

    # Get all recipes to show them on the page
    recipes = Recipe.objects.all()
    if request.GET.get('search'):
        recipes = recipes.filter(recipe_name__icontains = request.GET.get('search'))
    context = {'recipes': recipes}
    return render(request, 'recipe.html', context)

# from django.http import HttpResponse
def delete_recipe(request, id):
    rec = Recipe.objects.get(id = id)
    rec.delete()
    print("Record Delete..")
    return redirect('/vege/recipe/')


def update_recipe(request, id):
    rec = Recipe.objects.get(id=id)
    if request.method == "POST":
        data = request.POST

        recipe_name = data.get('recipe_name')
        recipe_description = data.get('recipe_description')
        recipe_image = request.FILES.get('recipe_image')

        rec.recipe_name = recipe_name
        rec.recipe_description = recipe_description

        if recipe_image:
           rec.recipe_image =  recipe_image
        rec.save()
        return redirect('/vege/recipe/')
    context = {'recipes': rec}
    return render(request, 'update_recipe.html', context)


def login_page(request):
    if request.method == "POST":
        username = request.POST.get('username', '').strip()
        password = request.POST.get('password', '').strip()
        print(username,password)
        users = User.objects.filter(username = username).values()
        print(users)
        user = authenticate(username=username, password=password)
        print(user)
        if user is not None:
            login(request, user)
            return redirect('/vege/recipe/')
        else:
            messages.error(request, "Invalid credentials")
            return redirect('/vege/login_page/')
    return render(request, 'login_page.html')

from django.contrib import messages
def register(request):
    if request.method == "POST":
        first_name = request.POST.get('first_name')
        last_name = request.POST.get('last_name')
        username = request.POST.get('username')
        password = request.POST.get('password')
        # print(first_name, last_name, username, password)

        if User.objects.filter(username=username).exists():
            messages.info(request, "Username already exists")
            return redirect('/vege/register/')

        user = User.objects.create_user(
            username=username,
            password=password,
            first_name=first_name,
            last_name=last_name
        )
        messages.success(request, "Account created successfully")
        return redirect('/vege/register/')
    return render(request, 'register.html')


def logout_page(request):
    logout(request)
    return redirect('/vege/login_page/')

home/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <title>Home</title>
</head>
<body>
<a href="{% url 'home:index' %}">Home</a> | <a href="{% url 'home:contact' %}">Contact Us</a>

{% block start%}

{% endblock %}
</body>
</html>

home/templates/contact.html
{% extends "base.html" %}
{% block start %}
  <h1>This is Contact page</h1>
{% endblock %}

home/templates/index.html
{% extends "base.html" %}
{% block start %}
  <h1>This is index page</h1>

  <table class="table" border="1" cellpadding="10">
    <thead>
      <tr>
        <th>#</th>
        <th>Name</th>
        <th>Designation</th>
        <th>Age</th>
        <th>Age ≥ 30</th>
      </tr>
    </thead>
    <tbody>
      {% for p in peoples %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td>{{ p.Name }}</td>
        <td>{{ p.Designation }}</td>
        <td>{{ p.Age }}</td>
        <td>
        {% if p.Age >= 30 %}
            Yes
        {% else %}
            No
        {% endif %}
        </td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
{% endblock %}

vege/templates/base1.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Recipe | Home Page</title>

    <!-- Bootstrap 5 CSS CDN -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body class="bg-light">
{% if user.is_authenticated %}
<nav class="navbar bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand">Hello {{user}}</a>

    <form class="d-flex ms-auto me-2" action="/vege/recipe/" method="get">
      <input class="form-control me-2" name="search" type="text" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success" type="submit">Search</button>
    </form>

    <form action="/vege/logout_page/" method="get">
      <button class="btn btn-outline-danger" type="submit">Logout</button>
    </form>
     {% else %}
      <div class="container-fluid">

    <form class="text-end ms-auto me-2" action="/vege/login_page/" method="get">
      <button class="btn btn-outline-danger" type="submit">Login</button>
    </form>
  </div>
</nav>
{% endif %}
{% block start%}

{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"></script>

</body>
</html>

vege/templates/login_page.html
{% extends 'base1.html' %}
{% block start %}
<body>
  <form method="POST" class="card-2 shadow p-5">
    {% csrf_token %}
    {% if messages %}
      {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible fade show" role="alert">
          {{ message }}
          <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
      {% endfor %}
    {% endif %}

    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Username</label>
      <input type="text" name="username" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Password</label>
      <input type="password" name="password" class="form-control" id="exampleInputPassword1">
    </div>
    <p>Don't have accounts? <a href="/vege/register/">Register</a> </p>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}

vege/templates/recipe.html
{% extends 'base1.html' %}
{% block start %}
<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-header bg-primary text-white">
            <h4 class="mb-0">Submit a Recipe</h4>
        </div>
        <div class="card shadow-lg p-5">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="recipeName" class="form-label">Recipe Name</label>
                    <input type="text" class="form-control" id="recipeName" name="recipe_name" placeholder="e.g. Paneer Butter Masala" required>
                </div>

                <div class="mb-3">
                    <label for="recipeDesc" class="form-label">Recipe Description</label>
                    <textarea class="form-control" id="recipeDesc" name="recipe_description" rows="4" placeholder="Briefly describe the recipe..." required></textarea>
                </div>

                <div class="mb-3">
                    <label for="recipeImage" class="form-label">Recipe Image</label>
                    <input type="file" class="form-control" id="recipeImage" name="recipe_image" accept="image/*">
                </div>

                <button type="submit" class="btn btn-success w-100">Submit Recipe</button>
            </form>
            <hr>
<!--            <div class="mt-5">-->
<!--                <div class="mx-auto col-12">-->
<!--                    <form>-->
<!--                        <div class="mb-3">-->
<!--                            <label class="form-label">Search Food</label>-->
<!--                            <input name="search" type="text">-->
<!--                        </div>-->
<!--                        <button type="submit" class="btn btn-primary">Search</button>-->
<!--                    </form>-->
<!--                </div>-->
<!--            </div>-->
        </div>
    </div>

    {% if recipes %}
    <div class="card shadow-sm">
        <div class="card-body">
            <h5 class="card-title">Submitted Recipes</h5>
            <table class="table table-striped-columns">
                <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Recipe Name</th>
                        <th scope="col">Recipe Description</th>
                        <th scope="col">Recipe Image</th>
                        <th scope="col">Actions</th>
                    </tr>
                </thead>
                <tbody>
                    {% for recp in recipes %}
                    <tr>
                        <th scope="row">{{ forloop.counter }}</th>
                        <td>{{ recp.recipe_name }}</td>
                        <td>{{ recp.recipe_description }}</td>
                        <td>
                            {% if recp.recipe_image %}
                                <img src="{{ recp.recipe_image.url }}" alt="Recipe Image" width="100">
                            {% else %}
                                <em>No image</em>
                            {% endif %}
                        </td>
                        <td>
                            <a href="/vege/delete_recipe/{{recp.id}}" class="btn btn-danger">Delete</a>
                            <a href="/vege/update_recipe/{{recp.id}}" class="btn btn-success">Update</a>
                        </td>
                    </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
    {% endif %}
</div>
{% endblock %}

vege/templates/register.html
{% extends 'base1.html' %}
{% block start %}

<body>
  <form method="POST" class="card-2 shadow p-5">
    {% csrf_token %}
      {% if messages %}
      {{ message.tags }}
         <div class="alert alert-primary" role="alert">
          {% for message in messages %}
            {{ message }}
           {% endfor %}
         </div>
      {% endif %}

    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">First name</label>
      <input type="text" class="form-control" name="first_name" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Last name</label>
      <input type="text" class="form-control" name="last_name" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="exampleInputEmail1" class="form-label">Username</label>
      <input type="text" class="form-control" name="username" id="exampleInputEmail1" aria-describedby="emailHelp">
    </div>
    <div class="mb-3">
      <label for="exampleInputPassword1" class="form-label">Password</label>
      <input type="password" name="password" class="form-control" id="exampleInputPassword1">
    </div>
    <p>Already have accounts? <a href="/vege/login_page/">Login</a> </p>
    <button type="submit" class="btn btn-primary">Submit</button>
  </form>

{% endblock %}

vege/templates/update_recipe.html
{% extends 'base1.html' %}
{% block start %}
<body class="bg-light">

<div class="container mt-5">
    <div class="card shadow-sm">
        <div class="card-header bg-primary text-white">
            <h4 class="mb-0">Update Recipe</h4>
        </div>
        <div class="card shadow-lg p-5">
            <form action="" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="mb-3">
                    <label for="recipeName" class="form-label">Recipe Name</label>
                    <input type="text" class="form-control" value="{{recipes.recipe_name}}" id="recipeName" name="recipe_name" placeholder="e.g. Paneer Butter Masala" required>
                </div>

                <div class="mb-3">
                    <label for="recipeDesc" class="form-label">Recipe Description</label>
                    <textarea class="form-control" id="recipeDesc"  name="recipe_description" rows="4" placeholder="Briefly describe the recipe..." required>{{recipes.recipe_description}}</textarea>
                </div>

                <div class="mb-3">
                    <label for="recipeImage" class="form-label">Recipe Image</label>
                    <input type="file" class="form-control" id="recipeImage" name="recipe_image" accept="image/*">
                </div>

                <button type="submit" class="btn btn-success w-100">Update Recipe</button>
            </form>
        </div>
    </div>

</div>
{% endblock %}